### ISSUE TITLE
Getting error 500 when trying to spend

### ISSUE THREAD

**Issue by kryztoval** [aeternity/aepp-sdk-python#136] opened 2019-03-21 09:45 UTC
When trying to call spend I get an error message and it fails

## Expected Behavior
I was hopping the transaction went on without issues

## Current Behavior
it returns 
`Message ____________________________ Unknown error 500`

## Possible Solution
None found so far

## Steps to Reproduce
install aepp-sdk-python
install dependencies 
call 
/usr/local/bin/python3 /opt/aepp-sdk-python/aecli -u http://ae.criesca.net:3013 -d http://ae.criesca.net:3013 account spend wallet ak_8KhtR5q1XWBz6VSFK1HynbKBYxXxJyVmD5EzE8EAx3oeXBwKB 2000000000000000000 --password reallyweirdpasswordhex --network-id ae_mainnet

## Environment / Context
This issue affects the aeternity tipping bot directly because it can only retry for a few seconds before continuing or expecting an answer, also the error is not clear at all

## [Aeternity Node](https://github.com/aeternity/aeternity/releases) Version
"genesis_key_block_hash": "kh_pbtwgLrNu23k9PA6XCZnUbtsvEFeQGgavY4FS2do3QP8kcp2z",
"network_id": "ae_mainnet",
"node_revision": "368fba92972db352426c5b7ce49a682aacd3cab8",
"node_version": "2.0.0",
Python version 3.6.8

## Troubleshooting done
I pointed it to another node (namely the one used by the explorer ( roma-net.mdw.aepps.com ) and it failed in the same exact way. This error was not here before. I tried several versions of the aepp-sdk-python, starting with the roma supported one up to and including current develop branch

**Comment by noandrea** [comment] 2019-03-21 12:27
Hi @kryztoval, the 500 error is an http error returned from the node, can you get the logs from the node?


I have tried to spend on another node and I cannot reproduce the error:
```
aecli -u http://18.136.37.63:3013 account spend wallet ak_2YMkP2qDDQpoUGf7ETguHjPLGR9hE34MV6XoefBGkuPLZyuJEa  2000000000000000000 --wait  --network-id ae_mainnet --password ***
<spend transaction>
  <data>
    Tag _____________________________________________ 12
    Vsn _____________________________________________ 1
    Sender id _______________________________________ ak_REAu6DK8eqW5juKhGKTZo7svi1EcKxAsu7vq6yRUaNw4K6Ypg
    Recipient id ____________________________________ ak_2YMkP2qDDQpoUGf7ETguHjPLGR9hE34MV6XoefBGkuPLZyuJEa
    Amount __________________________________________ 2000000000000000000
    Fee _____________________________________________ 16860000000000
    Ttl _____________________________________________ 0
    Nonce ___________________________________________ 3
    Payload _________________________________________ 
  </data>
  Metadata
  Tx ________________________________________________ tx_+KMLAfhCuEDU5rElkvCFQmF8FWokeD9PlLwX7ZHYVa0r/RreBTo7Xi2NgLgqmiU58MEyOrhqHWLS8Vm4J/8lZ/rHNxP3DNAPuFv4WQwBoQE3ArNgfdSENAyDj62+HrTamcCQMBT3YS6Do12LJb96/aEByuXL0UumZhbiwpuZsTQuYSDEaE/VRMLYTHCQkjKFmpmIG8FtZ07IAACGD1WGT5gAAAOAUBc48w==
  Hash ______________________________________________ th_2ZD83m4zMV4NvoiCwtE7sQuV8CWBXYavustPdHNyLbNZyCMAXU
  Signature _________________________________________ sg_UrWH7LFzHfBaPRPG79zJhXu4vg6mGx4AnGMp5j1XZyWpubctWRi1xz3meKD7G4FTxLwmRViu3yC4W7UYaNwtJotQVPw92
  Network id ________________________________________ ae_mainnet
</spend transaction>
```

using the node:

```
 aecli -u http://18.136.37.63:3013 chain status
<status for node at http://18.136.37.63:3013 >
  Difficulty ________________________________________ 50199919987843
  Genesis key block hash ____________________________ kh_pbtwgLrNu23k9PA6XCZnUbtsvEFeQGgavY4FS2do3QP8kcp2z
  Listening _________________________________________ True
  Network id ________________________________________ ae_mainnet
  Node revision _____________________________________ 3215a8608d0a77c7fac423be2d1dd3620a9bb5e0
  Node version ______________________________________ 2.1.0
  Peer count ________________________________________ 17789
  Pending transactions count ________________________ 3
  <protocols 2>
    <protocol #1>
      Effective at height ___________________________ 47800
      Version _______________________________________ 2
    </protocol #1>
    <protocol #2>
      Effective at height ___________________________ 0
      Version _______________________________________ 1
    </protocol #2>
  </protocols>
  Solutions _________________________________________ 0
  Sync progress _____________________________________ 100.0
  Syncing ___________________________________________ False
</status for node at http://18.136.37.63:3013 >
```

with the the sdk version 2.0.0

**Comment by kryztoval** [comment] 2019-03-21 23:29
[error.log.gz](https://github.com/aeternity/aepp-sdk-python/files/2994326/error.log.gz)
Here is the log shown by the node, I removed all the lines that said "Got invalid light micro_block"

**Comment by noandrea** [comment] 2019-03-22 10:51
can you get the `crash.log` too?  
I see those errors in the log and there should be more info in the `crash.log`:

```
22:56:23.271 [error] CRASH REPORT Process <0.21370.221> with 0 neighbours exited with reason: {timeout,{gen_server,call,[aec_tx_pool,{push,{signed_tx,{aetx,spend_tx,aec_spend_tx,91,{spend_tx,{id,account,<<88,40,232,205,122,15,33,106,71,55,9,120,224,205,172,245,229,184,11,78,117,200,173,230,202,134,96,225,153,240,241,84>>},{id,account,<<3,173,120,251,126,217,172,236,34,161,102,184,250,104,163,129,105,94,204,170,190,120,67,1,217,207,127,156,10,16,172,197>>},1000000000000000000,16860000000000,0,25,<<>>}},[<<53,223,38,206,159,81,101,141,36,54,143,179,114,133,206,12,126,188,233,188,245,...>>]},...}]}} in gen_server:call/2 line 206 in gen_server:call/2 line 206
22:56:23.271 [error] Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[external,<0.21005.221>,1,<0.21370.221>,{timeout,{gen_server,call,[aec_tx_pool,{push,{signed_tx,{aetx,spend_tx,aec_spend_tx,91,{spend_tx,{id,account,<<88,40,232,205,122,15,33,106,71,55,9,120,224,205,172,245,229,184,11,78,117,200,173,230,202,134,96,225,153,240,241,84>>},{id,account,<<3,173,120,251,126,217,172,236,34,161,102,184,250,104,163,129,105,94,204,170,190,120,67,1,217,207,127,156,10,16,172,197>>},1000000000000000000,16860000000000,0,25,<<>>}},[<<53,223,38,206,159,...>>]},...}]}},...]},...}}
```

**Comment by kryztoval** [comment] 2019-03-23 01:52
[crash.log.0.zip](https://github.com/aeternity/aepp-sdk-python/files/2998899/crash.log.0.zip)
this is the last crash log

**Comment by kryztoval** [comment] 2019-03-27 07:17
What else can i do to know what is going on?
This is starting to do it even when requesting just the balance, and it comes and goes, and I tried (as i said) this node roma-net.mdw.aepps.com and it does the exact same behavior, it also returns error 500

**Comment by noandrea** [comment] 2019-10-07 14:39
closing since not actual anymore

**Closed by noandrea** 2019-10-07 14:39 UTC
